/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Alert = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'alertModule' : IDL.Text,
  'timestamp' : IDL.Text,
  'severity' : IDL.Text,
  'project' : IDL.Text,
});
export const Asset = IDL.Record({
  'id' : IDL.Text,
  'degradationRate' : IDL.Float64,
  'maintenancePriority' : IDL.Text,
  'name' : IDL.Text,
  'sensorStatus' : IDL.Text,
  'lastInspection' : IDL.Text,
  'assetType' : IDL.Text,
  'healthScore' : IDL.Nat,
  'location' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'arbitrationExposure' : IDL.Float64,
  'costOverruns' : IDL.Float64,
  'totalProjects' : IDL.Nat,
  'totalPipelineValue' : IDL.Float64,
  'delayedProjects' : IDL.Nat,
  'onTrackPercent' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'completion' : IDL.Nat,
  'status' : IDL.Text,
  'delayDays' : IDL.Int,
  'projectType' : IDL.Text,
  'value' : IDL.Float64,
  'name' : IDL.Text,
  'costOverrun' : IDL.Float64,
  'state' : IDL.Text,
  'riskScore' : IDL.Nat,
  'contractor' : IDL.Text,
});
export const Tender = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'ministry' : IDL.Text,
  'l1Bid' : IDL.Float64,
  'l2Bid' : IDL.Float64,
  'clauses' : IDL.Vec(IDL.Text),
  'estimatedValue' : IDL.Float64,
  'fraudRisk' : IDL.Text,
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'activeProjects' : IDL.Nat,
  'credibilityScore' : IDL.Nat,
  'avgDelayDays' : IDL.Int,
  'completedProjects' : IDL.Nat,
  'financialHealth' : IDL.Text,
  'blacklisted' : IDL.Bool,
  'litigationCount' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateAIInsight' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], []),
  'getAssets' : IDL.Func([], [IDL.Vec(Asset)], []),
  'getDashboardStats' : IDL.Func([], [DashboardStats], []),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], []),
  'getTenders' : IDL.Func([], [IDL.Vec(Tender)], []),
  'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], []),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Alert = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'alertModule' : IDL.Text,
    'timestamp' : IDL.Text,
    'severity' : IDL.Text,
    'project' : IDL.Text,
  });
  const Asset = IDL.Record({
    'id' : IDL.Text,
    'degradationRate' : IDL.Float64,
    'maintenancePriority' : IDL.Text,
    'name' : IDL.Text,
    'sensorStatus' : IDL.Text,
    'lastInspection' : IDL.Text,
    'assetType' : IDL.Text,
    'healthScore' : IDL.Nat,
    'location' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'arbitrationExposure' : IDL.Float64,
    'costOverruns' : IDL.Float64,
    'totalProjects' : IDL.Nat,
    'totalPipelineValue' : IDL.Float64,
    'delayedProjects' : IDL.Nat,
    'onTrackPercent' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'completion' : IDL.Nat,
    'status' : IDL.Text,
    'delayDays' : IDL.Int,
    'projectType' : IDL.Text,
    'value' : IDL.Float64,
    'name' : IDL.Text,
    'costOverrun' : IDL.Float64,
    'state' : IDL.Text,
    'riskScore' : IDL.Nat,
    'contractor' : IDL.Text,
  });
  const Tender = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'ministry' : IDL.Text,
    'l1Bid' : IDL.Float64,
    'l2Bid' : IDL.Float64,
    'clauses' : IDL.Vec(IDL.Text),
    'estimatedValue' : IDL.Float64,
    'fraudRisk' : IDL.Text,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'activeProjects' : IDL.Nat,
    'credibilityScore' : IDL.Nat,
    'avgDelayDays' : IDL.Int,
    'completedProjects' : IDL.Nat,
    'financialHealth' : IDL.Text,
    'blacklisted' : IDL.Bool,
    'litigationCount' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateAIInsight' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], []),
    'getAssets' : IDL.Func([], [IDL.Vec(Asset)], []),
    'getDashboardStats' : IDL.Func([], [DashboardStats], []),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], []),
    'getTenders' : IDL.Func([], [IDL.Vec(Tender)], []),
    'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], []),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };