/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : string,
  'description' : string,
  'alertModule' : string,
  'timestamp' : string,
  'severity' : string,
  'project' : string,
}
export interface Asset {
  'id' : string,
  'degradationRate' : number,
  'maintenancePriority' : string,
  'name' : string,
  'sensorStatus' : string,
  'lastInspection' : string,
  'assetType' : string,
  'healthScore' : bigint,
  'location' : string,
}
export interface DashboardStats {
  'arbitrationExposure' : number,
  'costOverruns' : number,
  'totalProjects' : bigint,
  'totalPipelineValue' : number,
  'delayedProjects' : bigint,
  'onTrackPercent' : bigint,
}
export interface Project {
  'id' : string,
  'completion' : bigint,
  'status' : string,
  'delayDays' : bigint,
  'projectType' : string,
  'value' : number,
  'name' : string,
  'costOverrun' : number,
  'state' : string,
  'riskScore' : bigint,
  'contractor' : string,
}
export interface Tender {
  'id' : string,
  'status' : string,
  'title' : string,
  'ministry' : string,
  'l1Bid' : number,
  'l2Bid' : number,
  'clauses' : Array<string>,
  'estimatedValue' : number,
  'fraudRisk' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Vendor {
  'id' : string,
  'name' : string,
  'activeProjects' : bigint,
  'credibilityScore' : bigint,
  'avgDelayDays' : bigint,
  'completedProjects' : bigint,
  'financialHealth' : string,
  'blacklisted' : boolean,
  'litigationCount' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'generateAIInsight' : ActorMethod<[string], string>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAssets' : ActorMethod<[], Array<Asset>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getTenders' : ActorMethod<[], Array<Tender>>,
  'getVendors' : ActorMethod<[], Array<Vendor>>,
  'setGeminiApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];